-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 10:42:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema survey_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey_db` DEFAULT CHARACTER SET utf8 ;
USE `survey_db` ;

-- -----------------------------------------------------
-- Table `survey_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `phone_number` INT UNIQUE NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`addresses` (
  `address_id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(60) NOT NULL,
  `state` VARCHAR(60) NOT NULL,
  `country` VARCHAR(60) NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `idaddress_id_UNIQUE` (`address_id` ASC) VISIBLE,
  INDEX `fk_addresses_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `survey_db`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`surveys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`surveys` (
  `survey_id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`survey_id`),
  UNIQUE INDEX `survey_id_UNIQUE` (`survey_id` ASC) VISIBLE,
  INDEX `fk_surveys_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_surveys_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `survey_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`tags` (
  `tag` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`recommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`recommendations` (
  `recommendation_id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `surveys_survey_id` BIGINT NOT NULL,
  `tags_tag` BIGINT NOT NULL,
  PRIMARY KEY (`recommendation_id`),
  UNIQUE INDEX `recomendation_id_UNIQUE` (`recommendation_id` ASC) VISIBLE,
  INDEX `fk_recomendation_surveys1_idx` (`surveys_survey_id` ASC) VISIBLE,
  INDEX `fk_recommendations_tags1_idx` (`tags_tag` ASC) VISIBLE,
  CONSTRAINT `fk_recomendation_surveys1`
    FOREIGN KEY (`surveys_survey_id`)
    REFERENCES `survey_db`.`surveys` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recommendations_tags1`
    FOREIGN KEY (`tags_tag`)
    REFERENCES `survey_db`.`tags` (`tag`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`questions` (
  `question_id` BIGINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `surveys_survey_id` BIGINT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_questions_surveys1_idx` (`surveys_survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_surveys1`
    FOREIGN KEY (`surveys_survey_id`)
    REFERENCES `survey_db`.`surveys` (`survey_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`answers` (
  `answer_id` BIGINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `points` VARCHAR(45) NOT NULL,
  `index` ENUM('a', 'b', 'c', 'd') NOT NULL,
  `tags_tag` BIGINT NOT NULL,
  `questions_question_id` BIGINT NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_answer_tags1_idx` (`tags_tag` ASC) VISIBLE,
  INDEX `fk_answer_questions1_idx` (`questions_question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_tags1`
    FOREIGN KEY (`tags_tag`)
    REFERENCES `survey_db`.`tags` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_questions1`
    FOREIGN KEY (`questions_question_id`)
    REFERENCES `survey_db`.`questions` (`question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`responses` (
  `response_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`response_id`),
  UNIQUE INDEX `idresponse_UNIQUE` (`response_id` ASC) VISIBLE,
  INDEX `fk_responses_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_responses_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `survey_db`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey_db`.`selected_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey_db`.`selected_responses` (
  `selected_response_id` BIGINT NOT NULL,
  `index` ENUM('a', 'b', 'c', 'd') NOT NULL,
  `questions_question_id` BIGINT NOT NULL,
  `responses_response_id` BIGINT NOT NULL,
  PRIMARY KEY (`selected_response_id`),
  INDEX `fk_selected_responses_questions1_idx` (`questions_question_id` ASC) VISIBLE,
  INDEX `fk_selected_responses_responses1_idx` (`responses_response_id` ASC) VISIBLE,
  CONSTRAINT `fk_selected_responses_questions1`
    FOREIGN KEY (`questions_question_id`)
    REFERENCES `survey_db`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_selected_responses_responses1`
    FOREIGN KEY (`responses_response_id`)
    REFERENCES `survey_db`.`responses` (`response_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
